### PR TITLE
Cleanup of jobs screen.

### PR DESCRIPTION
**Pull request by hollance**

### CODE REVIEW

**Comment by jeroenleenarts** [comment]
Getting some crashes when loading app. Strangely it only happens when attached to the simulator with  debugger.

Steps:
1. Select iPhone 6 simulator
2. Reset contents and settings of simulator
3. Start app from xcode with debugger attached (CMD+R)
4. Tap Jobs icon
5. Tap Events icon
6. Rotate simulator left (CMD+Left)

Any thoughts?

**Comment by jeroenleenarts** [comment]
Crash seems to originate in Jobs controller.

Yup, there's a problem with multiple calls to loadObjects(). Not something you caused. Calling loadObjects all over the place was a bad move. This applies to all view controllers.

**Comment by hollance** [comment]
I've seen a crash very similar to this with the very first version I tried, but it's hard for me to reproduce. So I doubt it has anything to do with my recent changes. (It seems to be related to the split view controller.)

**Comment by jeroenleenarts** [comment]
Alright. I will do some debugging and working on it. I think it is result of not adhering to some implicit assumptions in the ParseUI classes. Assumptions made before you started working.

**Comment by jeroenleenarts** [comment]
Found problem. It's an existing problem. A number of calls result in loadObjects to be called. Also certain caching policies result in problemativ behavior.

Removing these items fixes crashing issues. But reintroduces some layout issues. Will merge and commit my changes that prevent crashes.

**Pull request merged**
